#include "global.h"

void *plugin;
bool expanded = false;
char *base_color = "";
char *normal = "";
char *roughness = "";
char *metallic = "";
char *height = "";
char *mask = "";

static void import_texture(char *path) {
	if (path != NULL && string_length(path) > 0) {
		import_texture_run(path, false);
	}
}

void on_ui() {
	if (ui_panel(&expanded, "Comfy Texture Bridge", false, false, false)) {
		ui_text("Paste local texture paths generated by the integration workspace.", 0, 0);
		ui_text_input(&base_color, "Base Color", UI_ALIGN_LEFT, true, false);
		ui_text_input(&normal, "Normal", UI_ALIGN_LEFT, true, false);
		ui_text_input(&roughness, "Roughness", UI_ALIGN_LEFT, true, false);
		ui_text_input(&metallic, "Metallic", UI_ALIGN_LEFT, true, false);
		ui_text_input(&height, "Height", UI_ALIGN_LEFT, true, false);
		ui_text_input(&mask, "Mask", UI_ALIGN_LEFT, true, false);

		if (ui_button("Import Texture Maps", UI_ALIGN_CENTER, "")) {
			import_texture(base_color);
			import_texture(normal);
			import_texture(roughness);
			import_texture(metallic);
			import_texture(height);
			import_texture(mask);
			console_info("Comfy texture maps imported.");
		}
	}
}

void main() {
	plugin = plugin_create();
	plugin_notify_on_ui(plugin, on_ui);
}
